### ISSUE TITLE
Any thoughts about captureing multiple screens?

### ISSUE THREAD

**Issue by Nriver** [ponty/pyscreenshot#48]
Here is the situation, I got more than one screen connected to my computer. And I can not capture the second screen with pyscreenshot. Tried to use coordinates outside the first screen, but only get blackout where I thought there will be the second screen's picture.

**Comment by phanirithvij** [comment]
ImageGrab does that but it's not for linux.
I have the same issue.

**Comment by ponty** [comment]
Please add more details!

All back-ends work with my setup:
- 2 full HD monitors
- Ubuntu 18.04 + X11

```python
grab(bbox=(500, 400, 2800, 600)
```

Full screen also works:
```
python -m pyscreenshot.examples.showgrabfullscreen
```

**Comment by petko10** [comment]
Referencing the coordinates works in specific cases, but it would be a nice option to target screens by index, since e.g. laptop +/- monitor setup are pretty common (where the setup changes frequently). That implies having a function to retrieve screen information (bboxes for all available screens). And I don't know if that's in the scope of pyscreenshot.

**Comment by ponty** [comment]
Screen indexing is a different topic. I don't know if it is possible at all.

**Comment by petko10** [comment]
It's possible on some platforms, Qt has the functionality on linux, but then again it's tricky in other cases. Thanks for the reply
